# run.yml — defines a single deck training run

deck: Modern-Prowess
version: 1
start_from_version: 1     # null = offline bootstrap, set to resume from checkpoint

generations: 1
games_per_gen: 4
replay_buffer_gens: 10

opponents:
  - deck: Modern-Goryos
    mode: mcts
    offline: true
  - deck: Standard-MonoG
    mode: mcts
    offline: true
  - deck: Standard-MonoR
    mode: mcts
    offline: true
  - deck: Standard-MonoU
    mode: mcts
    offline: true
  - deck: Standard-MonoW
    mode: mcts
    offline: true
  - deck: Standard16-GB
    mode: mcts
    offline: true
  - deck: Standard16-RB
    mode: mcts
    offline: true
  - deck: Standard16-UB
    mode: mcts
    offline: true
  - deck: Standard16-BW
    mode: mcts
    offline: true
  - deck: Standard16-RG
    mode: mcts
    offline: true
  - deck: Standard16-UG
    mode: mcts
    offline: true
  - deck: Standard16-GW
    mode: mcts
    offline: true
  - deck: Standard16-UR
    mode: mcts
    offline: true
  - deck: Standard16-RW
    mode: mcts
    offline: true
  - deck: Standard16-UW
    mode: mcts
    offline: true
  - deck: Standard16-5C
    mode: mcts
    offline: true
training:
  analyze_dataset: true
  generate_plots: true
  eval_previous_model: true

log_level: ACTIONS           # ALL | GAMEPLAY | ACTIONS | ERROR

curriculum: configs/curriculum.yml
max_jvms: 2